sudo: false
dist: xenial
language: ruby
rvm:
  - 2.7.1
branches:
  only:
      - master
addons:
  apt:
    packages:
      - libmagic-dev
      - libicu-dev
services:
  - mysql
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.0-amd64.deb
  - sudo dpkg -i --force-confnew elasticsearch-7.5.0-amd64.deb
  - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
  - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
  - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo systemctl start elasticsearch
install:
  - gem install bundler
  - bundle install
before_script:
  - sleep 10
  - cp config/settings/test.yml.sample config/settings/test.yml
  - RACK_ENV=test
  - rake db:create:all
  - rake db:schema:load
  - rake db:migrate
  - ./bin/populate_search.rb --rebuild
