sudo: false
dist: xenial
language: ruby
rvm:
  - 2.7.1
branches:
  only:
      - master
addons:
  apt:
    packages:
      - libmagic-dev
      - libicu-dev
services:
  - mysql
  - elasticsearch
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.1-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.9.1-amd64.deb && sudo service elasticsearch restart
install:
  - gem install bundler
  - bundle install
before_script:
  - sleep 10
  - cp config/settings/test.yml.sample config/settings/test.yml
  - RACK_ENV=test
  - rake db:create:all
  - rake db:schema:load
  - rake db:migrate
  - ./bin/populate_search.rb --rebuild
